"""add human reviews table

Revision ID: 271609799ee4
Revises: 8329f8ec9608
Create Date: 2026-09-05 02:47:15.334438
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '271609799ee4'
down_revision: str | None = '8329f8ec9608'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('human_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recovery_case_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('proposed_strategy', sa.String(length=40), nullable=True),
    sa.Column('decision_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('amount_at_risk_paise', sa.BigInteger(), nullable=False),
    sa.Column('reviewer', sa.String(length=120), nullable=True),
    sa.Column('decision_notes', sa.Text(), nullable=True),
    sa.Column('chosen_strategy', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount_at_risk_paise >= 0', name=op.f('ck_human_reviews_review_amount_non_negative')),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], name=op.f('fk_human_reviews_recovery_case_id_recovery_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_human_reviews'))
    )
    op.create_index('ix_human_reviews_case', 'human_reviews', ['recovery_case_id'], unique=False)
    op.create_index('ix_human_reviews_status', 'human_reviews', ['status', 'amount_at_risk_paise'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_human_reviews_status', table_name='human_reviews')
    op.drop_index('ix_human_reviews_case', table_name='human_reviews')
    op.drop_table('human_reviews')
    # ### end Alembic commands ###
