"""initial schema: merchants, customers, recovery_cases, audit_events

Revision ID: 2f367f4b81a9
Revises: 
Create Date: 2026-09-02 14:30:22.007834
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = '2f367f4b81a9'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('high_value_threshold_paise', sa.BigInteger(), nullable=False),
    sa.Column('policy_config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('high_value_threshold_paise >= 0', name=op.f('ck_merchants_high_value_threshold_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchants'))
    )
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('external_ref', sa.String(length=100), nullable=False),
    sa.Column('segment', sa.String(length=50), nullable=False),
    sa.Column('contactable_email', sa.Boolean(), nullable=False),
    sa.Column('contactable_sms', sa.Boolean(), nullable=False),
    sa.Column('do_not_contact', sa.Boolean(), nullable=False),
    sa.Column('preferred_language', sa.String(length=16), nullable=True),
    sa.Column('tenure_days', sa.Integer(), nullable=False),
    sa.Column('prior_successful_payments', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_customers_merchant_id_merchants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('merchant_id', 'external_ref', name='customer_external_ref')
    )
    op.create_table('recovery_cases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('merchant_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_external_id', sa.String(length=120), nullable=False),
    sa.Column('amount_at_risk_paise', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('failure_category', sa.String(length=40), nullable=False),
    sa.Column('failure_reason_code', sa.String(length=80), nullable=True),
    sa.Column('recoverability', sa.String(length=20), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('current_state', sa.String(length=20), nullable=False),
    sa.Column('recoverability_score', sa.Float(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=60), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recovered_amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('recovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('do_not_contact', sa.Boolean(), nullable=False),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_at_risk_paise > 0', name=op.f('ck_recovery_cases_amount_at_risk_positive')),
    sa.CheckConstraint('attempt_count >= 0', name=op.f('ck_recovery_cases_attempt_count_non_negative')),
    sa.CheckConstraint('recovered_amount_paise <= amount_at_risk_paise', name=op.f('ck_recovery_cases_recovered_not_exceeding_at_risk')),
    sa.CheckConstraint('recovered_amount_paise >= 0', name=op.f('ck_recovery_cases_recovered_amount_non_negative')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_recovery_cases_customer_id_customers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_recovery_cases_merchant_id_merchants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recovery_cases')),
    sa.UniqueConstraint('merchant_id', 'source_external_id', name='case_source_external_id')
    )
    op.create_index('ix_recovery_cases_detected_at', 'recovery_cases', ['detected_at'], unique=False)
    op.create_index('ix_recovery_cases_merchant_state', 'recovery_cases', ['merchant_id', 'current_state'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recovery_case_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.String(length=120), nullable=True),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('before_state', sa.String(length=20), nullable=True),
    sa.Column('after_state', sa.String(length=20), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sequence > 0', name=op.f('ck_audit_events_sequence_positive')),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], name=op.f('fk_audit_events_recovery_case_id_recovery_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events')),
    sa.UniqueConstraint('recovery_case_id', 'sequence', name='audit_sequence_per_case')
    )
    op.create_index('ix_audit_events_case_seq', 'audit_events', ['recovery_case_id', 'sequence'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_audit_events_case_seq', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index('ix_recovery_cases_merchant_state', table_name='recovery_cases')
    op.drop_index('ix_recovery_cases_detected_at', table_name='recovery_cases')
    op.drop_table('recovery_cases')
    op.drop_table('customers')
    op.drop_table('merchants')
    # ### end Alembic commands ###
