"""add interventions, recovery outcomes and experiment arm

Revision ID: ca39b8700991
Revises: dc4b7117fdf3
Create Date: 2026-09-02 23:36:25.711337
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = 'ca39b8700991'
down_revision: str | None = 'dc4b7117fdf3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interventions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recovery_case_id', sa.Uuid(), nullable=False),
    sa.Column('strategy', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('planned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_cost_paise', sa.BigInteger(), nullable=False),
    sa.Column('policy_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('decision_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempt_number > 0', name=op.f('ck_interventions_attempt_number_positive')),
    sa.CheckConstraint('estimated_cost_paise >= 0', name=op.f('ck_interventions_cost_non_negative')),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], name=op.f('fk_interventions_recovery_case_id_recovery_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_interventions')),
    sa.UniqueConstraint('idempotency_key', name='intervention_idempotency_key')
    )
    op.create_index('ix_interventions_case', 'interventions', ['recovery_case_id', 'attempt_number'], unique=False)
    op.create_table('recovery_outcomes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recovery_case_id', sa.Uuid(), nullable=False),
    sa.Column('intervention_id', sa.Uuid(), nullable=True),
    sa.Column('outcome_type', sa.String(length=30), nullable=False),
    sa.Column('amount_recovered_paise', sa.BigInteger(), nullable=False),
    sa.Column('external_event_id', sa.String(length=160), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_recovered_paise >= 0', name=op.f('ck_recovery_outcomes_outcome_amount_non_negative')),
    sa.ForeignKeyConstraint(['intervention_id'], ['interventions.id'], name=op.f('fk_recovery_outcomes_intervention_id_interventions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], name=op.f('fk_recovery_outcomes_recovery_case_id_recovery_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recovery_outcomes')),
    sa.UniqueConstraint('external_event_id', name='outcome_external_event_id')
    )
    op.create_index('ix_recovery_outcomes_case', 'recovery_outcomes', ['recovery_case_id', 'observed_at'], unique=False)
    # NOT NULL on a populated table needs a default for the existing rows.
    # Backfill everything as TREATMENT (the pre-experiment behaviour), then drop
    # the server default so the application layer owns it from here on.
    op.add_column(
        "recovery_cases",
        sa.Column(
            "experiment_arm",
            sa.String(length=20),
            nullable=False,
            server_default="TREATMENT",
        ),
    )
    op.alter_column("recovery_cases", "experiment_arm", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recovery_cases', 'experiment_arm')
    op.drop_index('ix_recovery_outcomes_case', table_name='recovery_outcomes')
    op.drop_table('recovery_outcomes')
    op.drop_index('ix_interventions_case', table_name='interventions')
    op.drop_table('interventions')
    # ### end Alembic commands ###
