"""add days overdue and checkout stage

Revision ID: f5d20832cafd
Revises: 271609799ee4
Create Date: 2026-09-05 10:45:50.357462
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'f5d20832cafd'
down_revision: str | None = '271609799ee4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_cases', sa.Column('days_overdue', sa.Integer(), nullable=True))
    op.add_column('recovery_cases', sa.Column('checkout_stage', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recovery_cases', 'checkout_stage')
    op.drop_column('recovery_cases', 'days_overdue')
    # ### end Alembic commands ###
